### ISSUE TITLE
Combat Extended fragmentation charge slowdown

### ISSUE THREAD

**Issue by jecrell** [jecrell/DoorsExpanded#4]
***Issue***
(As reported by TC_One)
TC_One: @Jecrell Got an incompatibility with Doors Expanded to report. I've not a single idea what can possible cause this, but whenever a frag grenade or mortar shell in Combat Extended explodes game freezes for ~10 seconds or so, to precess all the schrapnel. Without Doors Expanded processing takes milliseconds and lag is little to not notable at all.
There are no errors or warnings in console, so I can't help pinpointing the issue, just know that it's Doors Expanded for sure. Tried with and without DE and performance with explosions changes a LOT.

***Proposed Solution***
Investigate Combat Extended code. Find fragmentation damage handler. Find all Door references.

**Comment by Maeyanie** [comment]
I also noticed this, and oddly, it happens even on a freshly-spawned map without any doors having been built.

The code for spawning the fragmentation is (I think) here: [CompExplosiveCE.cs](https://github.com/NoImageAvailable/CombatExtended/blob/master/Source/CombatExtended/CombatExtended/Comps/CompExplosiveCE.cs)
The projectile code is here: [ProjectileCE.cs](https://github.com/NoImageAvailable/CombatExtended/blob/master/Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs)

**Comment by Maeyanie** [comment]
The CE developer had a few ideas on what might cause this, but I'm not sure if any of it would happen without a door even being placed on the map. [Details here](https://github.com/NoImageAvailable/CombatExtended/issues/621)
