### ISSUE TITLE
Friendlies can't open doors and get trapped.

### ISSUE THREAD

**Issue by isacmms** [jecrell/DoorsExpanded#7]
While checking raid generation (enemies vs allies), the game alerted about the ally pawns that entered my base walls were trapped and would dig out to escape.

Isolated Doors Expanded mod and made a friendly raid land inside my walls:

(Just right after landing)
![raidfriendly_trapped_dig_escape](https://user-images.githubusercontent.com/12188263/43857220-0ba3f1a4-9b21-11e8-8b77-841d8d31c2a5.png)

(This door was not hold open)
![digging](https://user-images.githubusercontent.com/12188263/43857297-4cd99f8e-9b21-11e8-8b19-a4669ae5ab0d.png)

LOG
https://git.io/fNSpN

Additional info:
-Other user reported having to hold the door open, so his guests would be able to leave.
-Pawns give up digging some seconds after holding the door open.
-The pawns that got trapped first, didn't land inside the walls. They managed to get in somehow, while crossing the map to reach their enemies - my base was in between of both groups. No door was open at that moment, it's like they could open the door to enter, but not to leave.

**Comment by jecrell** [comment]
Fixed in the previous release
